

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "11111:11111"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - keyguard-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "11112:11112"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - NEURA_ROUTER_API_KEY=${NEURA_ROUTER_API_KEY}
      - NEURA_ROUTER_API_URL=${NEURA_ROUTER_API_URL}
      - NEURA_ROUTER_API_MODEL=${NEURA_ROUTER_API_MODEL}
      - RUST_LOG=info
    networks:
      - keyguard-network

networks:
  keyguard-network:
    driver: bridge

volumes:
  keyguard-data:
